using System;

namespace OfisHal.Web.Models
{
    public class TohalLogFatura
    {
        public DateTime Zaman { get; set; }
        public int KullaniciId { get; set; }
        public byte Islem { get; set; }
        public int FaturaId { get; set; }
        public int? OCariKartId { get; set; }
        public int? SCariKartId { get; set; }
        public byte? OTip { get; set; }
        public byte? STip { get; set; }
        public DateTime? OTarih { get; set; }
        public DateTime? STarih { get; set; }
        public string OFaturaNo { get; set; }
        public string SFaturaNo { get; set; }
        public string OIrsaliyeNo { get; set; }
        public string SIrsaliyeNo { get; set; }
        public string OUnvan { get; set; }
        public string SUnvan { get; set; }
        public double? ORusum { get; set; }
        public double? SRusum { get; set; }
        public double? OIskontoOrani { get; set; }
        public double? SIskontoOrani { get; set; }
        public double? ORusumKdvOrani { get; set; }
        public double? SRusumKdvOrani { get; set; }
        public double? OIskonto { get; set; }
        public double? SIskonto { get; set; }
        public double? ORusumKdv { get; set; }
        public double? SRusumKdv { get; set; }
        public double? OKdvsizIadesizKap { get; set; }
        public double? SKdvsizIadesizKap { get; set; }
        public double? OKdvliIadesizKap { get; set; }
        public double? SKdvliIadesizKap { get; set; }
        public double? OIadesizKapKdvOrani { get; set; }
        public double? SIadesizKapKdvOrani { get; set; }
        public double? OIadesizKapKdv { get; set; }
        public double? SIadesizKapKdv { get; set; }
        public double? OYukleme { get; set; }
        public double? SYukleme { get; set; }
        public byte? ORehinIadeliKap { get; set; }
        public byte? SRehinIadeliKap { get; set; }
        public double? OYuklemeKdvOrani { get; set; }
        public double? SYuklemeKdvOrani { get; set; }
        public double? OYuklemeKdv { get; set; }
        public double? SYuklemeKdv { get; set; }
        public double? ONakliye { get; set; }
        public double? SNakliye { get; set; }
        public double? ONakliyeKdvOrani { get; set; }
        public double? SNakliyeKdvOrani { get; set; }
        public double? ONakliyeKdv { get; set; }
        public double? SNakliyeKdv { get; set; }
        public bool? OKesildi { get; set; }
        public bool? SKesildi { get; set; }
        public int? OVade { get; set; }
        public int? SVade { get; set; }
        public bool? ODegistirildi { get; set; }
        public bool? SDegistirildi { get; set; }
        public int? OMagazaId { get; set; }
        public int? SMagazaId { get; set; }
        public DateTime? OIrsaliyeZamani { get; set; }
        public DateTime? SIrsaliyeZamani { get; set; }
        public int? OSiparisId { get; set; }
        public int? SSiparisId { get; set; }
        public bool? OIhracatci { get; set; }
        public bool? SIhracatci { get; set; }
        public string OPlakaNo { get; set; }
        public string SPlakaNo { get; set; }
        public byte? ORusumKdvIliskisi { get; set; }
        public byte? SRusumKdvIliskisi { get; set; }
        public int? OTeslimatYeriId { get; set; }
        public int? STeslimatYeriId { get; set; }
        public bool? OVeresiye { get; set; }
        public bool? SVeresiye { get; set; }
        public double? OMalIskontoToplami { get; set; }
        public double? SMalIskontoToplami { get; set; }
        public string OAdres { get; set; }
        public string SAdres { get; set; }
        public byte? OKisilikTipi { get; set; }
        public byte? SKisilikTipi { get; set; }
        public int? OVergiDairesiId { get; set; }
        public int? SVergiDairesiId { get; set; }
        public string OVergiKimlikNo { get; set; }
        public string SVergiKimlikNo { get; set; }
        public DateTime? OGuncellemeZamani { get; set; }
        public DateTime? SGuncellemeZamani { get; set; }
        public int? OYerId { get; set; }
        public int? SYerId { get; set; }
        public string OGsmNo { get; set; }
        public string SGsmNo { get; set; }
        public string OEPosta { get; set; }
        public string SEPosta { get; set; }
        public byte? OGidecegiYerTipi { get; set; }
        public byte? SGidecegiYerTipi { get; set; }
        public byte? OSifati { get; set; }
        public byte? SSifati { get; set; }
        public byte? OBildirimTuru { get; set; }
        public byte? SBildirimTuru { get; set; }
        public byte? OCariSifati { get; set; }
        public byte? SCariSifati { get; set; }
        public int? OHalId { get; set; }
        public int? SHalId { get; set; }
        public int? OHksWebSiraNo { get; set; }
        public int? SHksWebSiraNo { get; set; }
        public DateTime? OZaman { get; set; }
        public DateTime? SZaman { get; set; }
        public byte? OHksMalinNiteligi { get; set; }
        public byte? SHksMalinNiteligi { get; set; }
        public int? OFisId { get; set; }
        public int? SFisId { get; set; }
        public int? OBagkurDosyaId { get; set; }
        public int? SBagkurDosyaId { get; set; }
        public int? OTeslimatSekliId { get; set; }
        public int? STeslimatSekliId { get; set; }
        public int? OUlasimSekliId { get; set; }
        public int? SUlasimSekliId { get; set; }
        public int? OOdemeSekliId { get; set; }
        public int? SOdemeSekliId { get; set; }
        public int? OIhracatParaBirimiId { get; set; }
        public int? SIhracatParaBirimiId { get; set; }
        public double? OIhracatKuru { get; set; }
        public double? SIhracatKuru { get; set; }
        public double? ONavlunMaliyeti { get; set; }
        public double? SNavlunMaliyeti { get; set; }
        public double? OSigortaMaliyeti { get; set; }
        public double? SSigortaMaliyeti { get; set; }
        public int? OFiyatReferansFaturaId { get; set; }
        public int? SFiyatReferansFaturaId { get; set; }
        public string OOdeyenKurumunVergiNosu { get; set; }
        public string SOdeyenKurumunVergiNosu { get; set; }
        public int? OOdeyenKurumunVergiDaireId { get; set; }
        public int? SOdeyenKurumunVergiDaireId { get; set; }
        public double? ONakitTahsilat { get; set; }
        public double? SNakitTahsilat { get; set; }
        public double? OKrediKartiTahsilati { get; set; }
        public double? SKrediKartiTahsilati { get; set; }
        public int? OPosCihaziId { get; set; }
        public int? SPosCihaziId { get; set; }
    }
}