using System;

namespace OfisHal.Core.Domain
{
    public class TohalTanim
    {
        public string Surum { get; set; }
        public byte? Tip { get; set; }
        public double? DokRusumOrani { get; set; }
        public double? DokBagkurOrani { get; set; }
        public double? DokBorsaOrani { get; set; }
        public double? DokStopajOrani { get; set; }
        public double? DokBorsaStopajOrani { get; set; }
        public double? DokKomisyonOrani { get; set; }
        public double? DokKomisyonKdvOrani { get; set; }
        public double? DokTuccarKapKdvOrani { get; set; }
        public double? DokNavlunKdvOrani { get; set; }
        public double? DokBirimHamaliye { get; set; }
        public double? DokBirimNakliye { get; set; }
        public bool? DokDokumDefteriVar { get; set; }
        public byte? DokDokumAmbar { get; set; }
        public byte? DokDokumDefterTipi { get; set; }
        public double? SatVerMukMalKdvOrani { get; set; }
        public double? SatIadesizKapKdvOrani { get; set; }
        public double? SatDigerMalKdvOrani { get; set; }
        public double? SatYuklemeKdvOrani { get; set; }
        public double? SatNakliyeKdvOrani { get; set; }
        public double? SatRusumOrani { get; set; }
        public byte? SatKiloOkumaSekli { get; set; }
        public bool? SatCiftciTuccarKdv { get; set; }
        public bool? SatKdvAtlama { get; set; }
        public bool? SatRusumAtlama { get; set; }
        public bool? SatDaraDaraliAtlama { get; set; }
        public bool? SatDaraRehinIliski { get; set; }
        public bool? SatAyniMallariTopla { get; set; }
        public bool? SatMalariSirala { get; set; }
        public bool? SatSatirdaFiatKontrol { get; set; }
        public byte? DigRehinTahsilatGosterimi { get; set; }
        public bool? SatVeresiyeUyarisi { get; set; }
        public bool? SatFaturadaKapCiksin { get; set; }
        public string DigSicilKodu { get; set; }
        public bool? SatRehinOtomatikHesaplansin { get; set; }
        public int? DigKiloOndalikSayisi { get; set; }
        public string DigYazihaneNo { get; set; }
        public int? DigFiyatKurusSayisi { get; set; }
        public int? DigBordroSayfaNo { get; set; }
        public int? DigMalBeyanSayfaNo { get; set; }
        public int? DigDokumDefterSayfaNo { get; set; }
        public byte? DigRehinIadeCalismaSekli { get; set; }
        public int? DigBordroKapDevri { get; set; }
        public double? DigBordroKiloDevri { get; set; }
        public string DigFirmaAdi { get; set; }
        public int? DigVergiDairesiId { get; set; }
        public string DigVergiKimlikNo { get; set; }
        public string DigTelefon { get; set; }
        public string DigAdres { get; set; }
        public string DigBelgeDizini { get; set; }
        public double? DigKasaDevri { get; set; }
        public int? HesNavlunHesabiId { get; set; }
        public int? HesRehinHesabiId { get; set; }
        public int? HesIadesizSandikHesabiId { get; set; }
        public int? HesRusumHesabiId { get; set; }
        public int? DigMustahsilKodSiraNo { get; set; }
        public int? DigMusteriKodSiraNo { get; set; }
        public bool? DigDokumNoBasinaSifir { get; set; }
        public bool? DigCariKodBasinaSifir { get; set; }
        public bool? DigFaturaNoBasinaSifir { get; set; }
        public byte? DigKasaVeresiyeSekli { get; set; }
        public bool? SatSatirdaNotVar { get; set; }
        public byte? DigEditDenetimIsleyisi { get; set; }
        public int? SatSatFaturaSiraNo { get; set; }
        public int? HesHamaliyeHesabiId { get; set; }
        public bool? DigKasaDefterindeDevirVar { get; set; }
        public int? DokFaturaSiraNo { get; set; }
        public bool? SatRehindeMarkaVar { get; set; }
        public byte? DigKasaDevirSekli { get; set; }
        public bool? DigRehinBakiyeGosterilsin { get; set; }
        public int? DigCariHareketRefNo { get; set; }
        public byte? SatRehinIadeIslenecegiHsp { get; set; }
        public bool? DigBuyukHarfeCevir { get; set; }
        public double? DokMustahsilCiroSiniri { get; set; }
        public int? DigOdemeBordroSiraNo { get; set; }
        public bool? SatIskontoVar { get; set; }
        public bool? DigOdemeBordroBasinaSifir { get; set; }
        public int? HesNakliyeHesabiId { get; set; }
        public double? DigVadeFarkiOrani { get; set; }
        public int? HesCiroPrimiHesabiId { get; set; }
        public DateTime? DigRehinBaslangicTarihi { get; set; }
        public DateTime? DonemOnayTarihi { get; set; }
        public string DigWebKullanicisi { get; set; }
        public string DigWebSifresi { get; set; }
        public int? DonemOnayGunSayisi { get; set; }
        public byte? SatFaturaMalGorunumSekli { get; set; }
        public bool? DokKapKomisyonaDahil { get; set; }
        public bool? DokOtomatikHamaliye { get; set; }
        public byte? DokHamaliyeHesaplamaSekli { get; set; }
        public string DevirAlani { get; set; }
        public DateTime? DigDonemBaslangicTarihi { get; set; }
        public DateTime? DigDonemBitisTarihi { get; set; }
        public byte? DokAyniMallariToplamaSekli { get; set; }
        public bool? IadeliKapTutarRehindenAl { get; set; }
        public byte? SatRusumKdvIliskisi { get; set; }
        public double? SatRusumKdvOrani { get; set; }
        public byte? DokDokumDefterGosterimi { get; set; }
        public bool? DigKunyeTakibiVar { get; set; }
        public string DigGsmNo { get; set; }
        public string DigEposta { get; set; }
        public string DigTopHaliAdi { get; set; }
        public string DigTopHaliTelNo { get; set; }
        public byte? DigGidecegiYerTipi { get; set; }
        public bool? DigKunyeBarkoduYazdir { get; set; }
        public int? DigYerId { get; set; }
        public byte? DigSifati { get; set; }
        public byte? SatBildirimTuru { get; set; }
        public byte? DigSatinAlaninSifati { get; set; }
        public bool? DigKunyeyiOtomatikGonder { get; set; }
        public int? DigHalId { get; set; }
        public bool? SatStokKunyesiDegistir { get; set; }
        public bool? SatDokumdenKunyeVar { get; set; }
        public DateTime? DigKunyeGecerlilikTarihi { get; set; }
        public byte? DigTutarHesaplamaSekli { get; set; }
        public bool? DokFiyatGirilsin { get; set; }
        public int? SatFaturaSatirSayisi { get; set; }
        public byte? DigKasMustahCalismaSekli { get; set; }
        public byte? DigSatisTipi { get; set; }
        public bool? SatKesilendeOranDegissin { get; set; }
        public string DegisiklikTakipSifresi { get; set; }
        public byte? DokBildirimTuru { get; set; }
        public byte? DigHksBildirimSekli { get; set; }
        public string DigHalMudurlukFormuKlasoru { get; set; }
        public string DigHksSifresi { get; set; }
        public byte? DigHksCalismaSekli { get; set; }
        public int? DigHksAdetSiniri { get; set; }
        public double? DigHksKiloSiniri { get; set; }
        public string DigYedekKlasoru { get; set; }
        public bool? DigEBagkurVar { get; set; }
        public bool? SatStokMiktariGoster { get; set; }
        public string FirMahalle { get; set; }
        public string FirCadde { get; set; }
        public string FirSokak { get; set; }
        public string FirKapiNo { get; set; }
        public string FirDaireNo { get; set; }
        public string FirPostaKodu { get; set; }
        public string KdvMuafiyetNedeni { get; set; }
        public string FirWebAdresi { get; set; }
        public string EFaturaOnEki { get; set; }
        public int? EFaturaSiraNo { get; set; }
        public string DigVergiSorgulayanTcKNo { get; set; }
        public bool? DigMarkaninKunyeTakibiVar { get; set; }
        public byte? HksKunyeBakiyesiDusmeSekli { get; set; }
        public bool? HksVarsayilanDegerAtansin { get; set; }
        public string HksVarsayilanPlakaNo { get; set; }
        public bool? SatSubeAdresiniKullan { get; set; }
        public int? HesStopajHesabiId { get; set; }
        public int? HesBorsaHesabiId { get; set; }
        public int? HesBagkurHesabiId { get; set; }
        public bool? SatKunyesizSatirlardaUyar { get; set; }
        public bool? HksSatirCogalabilir { get; set; }
        public string DigMudurlukKulAdi { get; set; }
        public string DigMudurlukKulSifresi { get; set; }
        public byte? DokCariyeIslemeSekli { get; set; }
        public bool? DokCariIslemeDegissin { get; set; }
        public bool? DokToplamaMalCalisir { get; set; }
        public byte? DigVeresiyeAsimOlayi { get; set; }
        public bool? SatRusumuHksdenAl { get; set; }
        public bool? SatKesilirkenKunyeAl { get; set; }
        public int? DokHizmetBedeliHesabiId { get; set; }
        public bool? SatDokumRusumuAsilabilir { get; set; }
        public int? EBelgeServerPortu { get; set; }
        public bool? SatSatisFatFiyatGelsin { get; set; }
        public double? AlsDigerMalKdvOrani { get; set; }
        public int? AlsFaturaSiraNo { get; set; }
        public bool? AlsFatFiyatGelsin { get; set; }
        public string DigSahisAdi { get; set; }
        public string DigSahisSoyadi { get; set; }
        public bool? DigAciklama2Goster { get; set; }
        public int? HesapYili { get; set; }
        public string FirMersisNo { get; set; }
        public string EntegratorCsvDizini { get; set; }
        public bool? HalMudurlukXmlAdi { get; set; }
        public bool? SatFaturaDefaultVeresiye { get; set; }
        public string EMustahsilFaturasiOnEki { get; set; }
        public int? EMustahsilFaturasiSiraNo { get; set; }
        public bool? SatBarkoduDirekYazdir { get; set; }
        public byte? SatBarkodBelgesi { get; set; }
        public int? SatIrsaliyeSiraNo { get; set; }
        public bool? SatIrsaliyeNoBasinaSifir { get; set; }
        public int? DigTuccarKodSiraNo { get; set; }
        public byte? HksStokCalismaSekli { get; set; }
        public bool? DokKapliEntegrasyonYap { get; set; }
        public bool? HksSatirDetayiVar { get; set; }
        public string DigIkinciYedekKlasoru { get; set; }
        public double? AlsRusumOrani { get; set; }
        public int? FisSiraNo { get; set; }
        public byte? SatBildirimServisi { get; set; }
        public bool? DigVeresiyeMizaniAc { get; set; }
        public bool? HksKunyeSecAcilsin { get; set; }
        public bool? DigKasaDevrindeYukNakVar { get; set; }
        public int? MalKabulSiraNo { get; set; }
        public string EArsivFaturasiOnEki { get; set; }
        public int? EArsivFaturasiSiraNo { get; set; }
        public bool? FirEArsivFaturasiGonderilsin { get; set; }
        public bool? EFaturaBasilsin { get; set; }
        public DateTime? EArsivBaslangicTarihi { get; set; }
        public bool? HksKiloKunyesiOncelikli { get; set; }
        public string HksOfiskunyeWebAdresi { get; set; }
        public bool? DigKasaDefterindeAlisVar { get; set; }
        public bool? SatPesinKayitYapilmasin { get; set; }
        public byte? AlsSiparisCalismaSekli { get; set; }
        public string EBelgeServerIp { get; set; }
        public DateTime? EFaturaBaslangicTarihi { get; set; }
        public byte? MusFatDuzenlemeSekli { get; set; }
        public bool? EArsivFaturasiBasilsin { get; set; }
        public DateTime? EMustahsilMakbuzuBaslangici { get; set; }
        public string EMustahsilMakbuzuOnEki { get; set; }
        public int? EMustahsilMakbuzuSiraNo { get; set; }
        public bool? EMustahsilMakbuzuBasilsin { get; set; }
        public DateTime? EIrsaliyeBaslangicTarihi { get; set; }
        public string EIrsaliyeOnEki { get; set; }
        public int? EIrsaliyeSiraNo { get; set; }
        public bool? EIrsaliyeBasilsin { get; set; }
        public string EMusFatArsivOnEki { get; set; }
        public int? EMusFatArsivSiraNo { get; set; }
        public string FirIbanNo { get; set; }
        public bool? SatTeslimatYeriKopyalansin { get; set; }
        public bool? XsltDosyalariKopyalansin { get; set; }
        public bool? RptDosyalariKopyalansin { get; set; }
        public bool? EIrsaliyedeFiyatVar { get; set; }
        public int? EntegratorYanitVermeSuresi { get; set; }
        public byte? EFaturaSenaryosu { get; set; }
        public byte? SatFaturaBelgesi { get; set; }
        public bool? EFaturaNotAdetOlsun { get; set; }
        public bool? EFaturaMustahsilVar { get; set; }
        public bool? DigRehinBazliKapCari { get; set; }
        public byte? SatRusumKdvGosterimi { get; set; }
        public double? SatKunyeFiyatiSinirOrani { get; set; }
        public byte? SatKunyeFiyatiSinirDenetim { get; set; }
        public byte? SatKunyePlakaNoKontrolu { get; set; }
        public bool? SatIadesizKapHesaplansin { get; set; }
        public bool? KunyeCogalmaLog { get; set; }
        public string DigBagkurDosyaNo { get; set; }
        public byte? SatHamaliyeHesaplamaSekli { get; set; }
        public byte? SatFaturaUyarmaSekli { get; set; }
        public bool? HksKiloKapKarisik { get; set; }
        public bool? DokSatirdaStokGirisTarihi { get; set; }
        public bool? SatOtomatikHamaliye { get; set; }
        public string FirBankaAdi { get; set; }
        public bool? DigKasaKrediKartiVar { get; set; }
        public bool? SatOtomatikNakliye { get; set; }
        public byte? SatNakliyeHesaplamaSekli { get; set; }
        public double? SatBirimKiloNakliye { get; set; }
        public double? SatBirimKapNakliye { get; set; }
        public string SatHamaliyeAdlandirma { get; set; }
        public string SatNakliyeAdlandirma { get; set; }
        public byte? AlsMalBakiyeHesaplamaSekli { get; set; }
        public DateTime? SonAlinanGibKullaniciTarih { get; set; }
        public string DigEtaFaturaKlasoru { get; set; }
        public string DigBagkurKullaniciAdi { get; set; }
        public string DigBagkurSifresi { get; set; }
        public string HksBildirimBelediyeAdi { get; set; }
        public string HksServisAdresi { get; set; }
        public bool? SatKunyedeListeFiyatiVar { get; set; }
        public bool? FirmalaraMakbuzKesilsin { get; set; }
        public byte? EFaturaYaziIleSekli { get; set; }
        public bool? EFaturaMustahsilVknVar { get; set; }
        public bool? HksDigerKunyeleriKullan { get; set; }
        public DateTime? DevirTarihi { get; set; }
        public string EFaturaExeYolu { get; set; }
        public string EFaturaPortalAdresi { get; set; }

        public virtual TohalHal DigHal { get; set; }
        public virtual TohalYer DigYer { get; set; }
        public virtual TohalHesap DokHizmetBedeliHesabi { get; set; }
        public virtual TohalHesap HesBagkurHesabi { get; set; }
        public virtual TohalHesap HesBorsaHesabi { get; set; }
        public virtual TohalHesap HesCiroPrimiHesabi { get; set; }
        public virtual TohalHesap HesHamaliyeHesabi { get; set; }
        public virtual TohalHesap HesIadesizSandikHesabi { get; set; }
        public virtual TohalHesap HesNakliyeHesabi { get; set; }
        public virtual TohalHesap HesNavlunHesabi { get; set; }
        public virtual TohalHesap HesRehinHesabi { get; set; }
        public virtual TohalHesap HesRusumHesabi { get; set; }
        public virtual TohalHesap HesStopajHesabi { get; set; }
    }
}