

using System;
using System.Collections.Generic;

namespace OfisHal.Core.Domain
{
    public class VohalMakbuz
    {
        public int MakbuzId { get; set; }
        public int MarkaId { get; set; }
        public string Marka { get; set; }
        public int CariKartId { get; set; }
        public string CariKodu { get; set; }
        public string CariAdi { get; set; }
        public byte KisilikTipi { get; set; }
        public string VergiKimlikNo { get; set; }
        public string DokumNo { get; set; }
        public DateTime StokGirisTarihi { get; set; }
        public DateTime? FaturaTarihi { get; set; }
        public DateTime? FaturaZamani { get; set; }
        public string FaturaNo { get; set; }
        public string IrsaliyeNo { get; set; }
        public string Plaka { get; set; }
        public string Aciklama { get; set; }
        public bool? Kesildi { get; set; }
        public double RusumOrani { get; set; }
        public double Rusum { get; set; }
        public double StopajOrani { get; set; }
        public double Stopaj { get; set; }
        public double BagkurOrani { get; set; }
        public double Bagkur { get; set; }
        public double BorsaOrani { get; set; }
        public double Borsa { get; set; }
        public double Navlun { get; set; }
        public double NavlunKdvOrani { get; set; }
        public double NavlunKdv { get; set; }
        public double KomisyonOrani { get; set; }
        public double Komisyon { get; set; }
        public double KomisyonKdvOrani { get; set; }
        public double KomisyonKdv { get; set; }
        public double IadeliKapTutari { get; set; }
        public double IadesizKapTutari { get; set; }
        public double IadesizKapKdvOrani { get; set; }
        public double IadesizKapKdv { get; set; }
        public bool? IadesizKapKomisyonaDahil { get; set; }
        public double? GelenMiktar { get; set; }
        public int? GelenKap { get; set; }
        public double? SatilanMiktar { get; set; }
        public int? SatilanKap { get; set; }
        public int? BekleyenHareketSayisi { get; set; }
        public double? MakbuzdakiMiktar { get; set; }
        public int? MakbuzdakiKap { get; set; }
        public double? Masraf { get; set; }
        public double? MasrafKdv { get; set; }
        public double? MalTutari { get; set; }
        public double? MalKdv { get; set; }
        public int? OrtakId { get; set; }
        public double OrtaklikOrani { get; set; }
        public string OrtakAdi { get; set; }
        public int? Vade { get; set; }
        public string EkleyenKullaniciAdi { get; set; }
        public DateTime EklemeZamani { get; set; }
        public string GuncelleyenKullaniciAdi { get; set; }
        public DateTime GuncellemeZamani { get; set; }
        public string MakbuzGuncelleyenKullaniciAdi { get; set; }
        public DateTime MakbuzGuncellemeZamani { get; set; }
        public string EPosta { get; set; }
        public string GsmNo { get; set; }
        public string KodTarih { get; set; }
        public string AdTarih { get; set; }
        public int? BeldeId { get; set; }
        public int? BeldeHksId { get; set; }
        public string BeldeAdi { get; set; }
        public int? IlceId { get; set; }
        public int? IlceHksId { get; set; }
        public string IlceAdi { get; set; }
        public int? IlId { get; set; }
        public int? IlHksId { get; set; }
        public string IlAdi { get; set; }
        public int? UlkeId { get; set; }
        public bool? BagkurHesaplanmasin { get; set; }
        public string UlkeAdi { get; set; }
        public byte? Sifati { get; set; }
        public byte? BildirimTuru { get; set; }
        public byte? HksMalinNiteligi { get; set; }
        public int? TeslimatYeriId { get; set; }
        public byte? TeslimatYeriTuru { get; set; }
        public string TeslimatYeriAdi { get; set; }
        public int? HksWebSiraNo { get; set; }
        public int? HalId { get; set; }
        public string HalAdi { get; set; }
        public byte CariyeIslemeSekli { get; set; }
        public int? BagkurDosyaId { get; set; }
        public string BagkurDosyaNo { get; set; }
        public bool? BagkurDosyasiMuhasebelesti { get; set; }
        public int? GibMuhatapPostaKutusuId { get; set; }
        public string GibMuhatapPostaKutusu { get; set; }
        public string GibFirmamizPostaKutusu { get; set; }
        public int? GibFirmamizPostaKutusuId { get; set; }
        public string EFaturaNot { get; set; }
        public string EFaturaBolgeKodu { get; set; }
        public int EkleyenId { get; set; }
        public string EFaturaMusteriAdi { get; set; }
        public string EFaturaVergiDairesi { get; set; }
        public string EFaturaVergiKimlikNo { get; set; }
        public int? EFaturaDaireNo { get; set; }
        public int? EFaturaKapiNo { get; set; }
        public int? EFaturaSokak { get; set; }
        public int? EFaturaCadde { get; set; }
        public string EFaturaMahalle { get; set; }
        public string EFaturaSemt { get; set; }
        public string EFaturaIlce { get; set; }
        public string EFaturaIl { get; set; }
        public string EFaturaUlke { get; set; }
        public string EFaturaTelefon { get; set; }
        public string EFaturaFaksi { get; set; }
        public string EFaturaEposta { get; set; }
        public string EFaturaWebAdresi { get; set; }
        public string EFaturaGsmNo { get; set; }
        public int? EFaturaPostaKodu { get; set; }
        public int RedDurumu { get; set; }
        public string EFaturaFaturaKodu { get; set; }
        public string EFaturaMalverenKodu { get; set; }
        public byte? EFaturaDurumu { get; set; }
        public int Tip { get; set; }
        public byte? BildirimDurumu { get; set; }
        public string DonenAlanDegeri { get; set; }
        public int Siralama { get; set; }
        public string EFaturaEttn { get; set; }
    }
}