using System;

namespace OfisHal.Core.Domain
{
    public class VohalFatura
    {
        public int FaturaId { get; set; }
        public string Guid { get; set; }
        public int Tip { get; set; }
        public int? CariKartId { get; set; }
        public string CariKod { get; set; }
        public string CariUnvan { get; set; }
        public string GsmNo { get; set; }
        public string EPosta { get; set; }
        public string ReferansNo { get; set; }
        public string FaturaNo { get; set; }
        public DateTime Tarih { get; set; }
        public DateTime Zaman { get; set; }
        public int? Vade { get; set; }
        public string Unvan { get; set; }
        public int? MagazaId { get; set; }
        public string MagazaKodu { get; set; }
        public int? SehirId { get; set; }
        public string SehirAdi { get; set; }
        public string Adres { get; set; }
        public byte KisilikTipi { get; set; }
        public int? VergiDairesiId { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiKimlikNo { get; set; }
        public string OdeyenKurumunVergiNosu { get; set; }
        public int? OdeyenKurumunVergiDaireId { get; set; }
        public string OdeyenKurumunVergiDairesi { get; set; }
        public string IrsaliyeNo { get; set; }
        public byte? GidecegiYerTipi { get; set; }
        public DateTime IrsaliyeZamani { get; set; }
        public int? SiparisId { get; set; }
        public string SiparisNo { get; set; }
        public double Rusum { get; set; }
        public double RusumKdvOrani { get; set; }
        public double RusumKdv { get; set; }
        public double IskontoOrani { get; set; }
        public double Iskonto { get; set; }
        public bool? IskontoHesaplanmasin { get; set; }
        public double MalIskontoToplami { get; set; }
        public double KdvsizIadesizKap { get; set; }
        public double KdvliIadesizKap { get; set; }
        public double IadesizKapKdvOrani { get; set; }
        public double IadesizKapKdv { get; set; }
        public byte RehinIadeliKap { get; set; }
        public double Yukleme { get; set; }
        public double YuklemeKdvOrani { get; set; }
        public double YuklemeKdv { get; set; }
        public double Nakliye { get; set; }
        public double NakliyeKdvOrani { get; set; }
        public double NakliyeKdv { get; set; }
        public bool? Kesildi { get; set; }
        public bool? Veresiye { get; set; }
        public double NakitTahsilat { get; set; }
        public double KrediKartiTahsilati { get; set; }
        public int? PosCihaziId { get; set; }
        public string PosCihaziAdi { get; set; }
        public bool? VeresiyeDurumuDegisti { get; set; }
        public bool? Degistirildi { get; set; }
        public int? IadeEdilenKapSayisi { get; set; }
        public bool? RehinDevri { get; set; }
        public int EkleyenId { get; set; }
        public string EkleyenKullaniciAdi { get; set; }
        public DateTime EklemeZamani { get; set; }
        public string GuncelleyenKullaniciAdi { get; set; }
        public DateTime GuncellemeZamani { get; set; }
        public string GuncellemeZamaniString { get; set; }
        public bool? Ihracatci { get; set; }
        public string PlakaNo { get; set; }
        public byte? RusumKdvIliskisi { get; set; }
        public int? BeldeId { get; set; }
        public int? BeldeHksId { get; set; }
        public string BeldeAdi { get; set; }
        public int? IlceId { get; set; }
        public int? IlceHksId { get; set; }
        public string IlceAdi { get; set; }
        public int? IlId { get; set; }
        public int? IlHksId { get; set; }
        public string IlAdi { get; set; }
        public byte? Sifati { get; set; }
        public byte? BildirimTuru { get; set; }
        public byte? CariSifati { get; set; }
        public int? HalId { get; set; }
        public string HalAdi { get; set; }
        public int? TeslimatYeriId { get; set; }
        public byte? TeslimatYeriTuru { get; set; }
        public string TeslimatYeriAdi { get; set; }
        public int? MarkaId { get; set; }
        public string Marka { get; set; }
        public int? SoforId { get; set; }
        public string SoforAdi { get; set; }
        public int? TeslimatYeriWebSiraNo { get; set; }
        public int? UlkeId { get; set; }
        public byte? HksMalinNiteligi { get; set; }
        public int? GidecegiYerWebSiraNo { get; set; }
        public int? GibFirmamizPostaKutusuId { get; set; }
        public string GibFirmamizPostaKutusu { get; set; }
        public int? GibMuhatapPostaKutusuId { get; set; }
        public string GibMuhatapPostaKutusu { get; set; }
        public int? GibFirmamizIrsaliyeKutusuId { get; set; }
        public string GibFirmamizIrsaliyeKutusu { get; set; }
        public int? GibMuhatapIrsaliyeKutusuId { get; set; }
        public string GibMuhatapIrsaliyeKutusu { get; set; }
        public string EFaturaEttn { get; set; }
        public byte? EFaturaSenaryosu { get; set; }
        public string EIrsaliyeEttn { get; set; }
        public int RedDurumu { get; set; }
        public int RehinVar { get; set; }
        public int MasrafVar { get; set; }
        public string EFaturaMusteriAdi { get; set; }
        public string EFaturaVergiDairesi { get; set; }
        public string EFaturaVergiKimlikNo { get; set; }
        public string EFaturaSemt { get; set; }
        public string EFaturaIlce { get; set; }
        public int? EFaturaPostaKodu { get; set; }
        public string EFaturaMahalle { get; set; }
        public int? EFaturaCadde { get; set; }
        public int? EFaturaSokak { get; set; }
        public int? EFaturaKapiNo { get; set; }
        public int? EFaturaDaireNo { get; set; }
        public string EFaturaIl { get; set; }
        public string EFaturaUlke { get; set; }
        public string EFaturaTelefon { get; set; }
        public string EFaturaFaksi { get; set; }
        public string EFaturaEposta { get; set; }
        public string EFaturaWebAdresi { get; set; }
        public string EFaturaGsmNo { get; set; }
        public double? VeresiyeSiniri { get; set; }
        public double? RiskSiniri { get; set; }
        public bool? Aktarildi { get; set; }
        public string EFaturaNot { get; set; }
        public string EFaturaBolgeKodu { get; set; }
        public string EFaturaSiparisNo { get; set; }
        public DateTime? EFaturaSiparisTarihi { get; set; }
        public string EFaturaFaturaKodu { get; set; }
        public string EFaturaMalverenKodu { get; set; }
        public int? FiyatListesiId { get; set; }
        public byte BildirimDurumu { get; set; }
        public byte OnBildirimDurumu { get; set; }
        public int? FisId { get; set; }
        public string FisNo { get; set; }
        public int? FiyatReferansFaturaId { get; set; }
        public string FiyatReferansFaturaNo { get; set; }
        public int? BagkurDosyaId { get; set; }
        public string BagkurDosyaNo { get; set; }
        public bool? BagkurDosyasiMuhasebelesti { get; set; }
        public int? IhracatParaBirimiId { get; set; }
        public string IhracatParaBirimi { get; set; }
        public string IhracatParaBirimiKisaltma { get; set; }
        public double? IhracatKuru { get; set; }
        public double? NavlunMaliyeti { get; set; }
        public double? SigortaMaliyeti { get; set; }
        public int? TeslimatSekliId { get; set; }
        public string TeslimatSekli { get; set; }
        public string TeslimatSekliKisaltma { get; set; }
        public int? UlasimSekliId { get; set; }
        public string UlasimSekli { get; set; }
        public string UlasimSekliKisaltma { get; set; }
        public int? OdemeSekliId { get; set; }
        public string OdemeSekli { get; set; }
        public string OdemeSekliKisaltma { get; set; }
        public double? CariKdvOrani { get; set; }
        public bool? FatKesilmedenKunyeAlinamaz { get; set; }
        public byte? CariHamaliyeHesaplamaSekli { get; set; }
        public byte? CariNakliyeHesaplamaSekli { get; set; }
        public bool? IadeFaturasi { get; set; }
    }
}