using System;

namespace OfisHal.Core.Domain
{
    public class VohalEIrsaliye
    {
        public int DepoFisiId { get; set; }
        public int FaturaId { get; set; }
        public string GondericiGibPostaKutusu { get; set; }
        public string AliciGibPostaKutusu { get; set; }
        public string RecipientId { get; set; }
        public int? GibMuhatapPostaKutusuId { get; set; }
        public string Id { get; set; }
        public string Uuid { get; set; }
        public DateTime IssueDate { get; set; }
        public DateTime IssueTime { get; set; }
        public DateTime ActualDespatchDate { get; set; }
        public DateTime ActualDespatchTime { get; set; }
        public string DespatchAdviceTypeCode { get; set; }
        public int? PaperId { get; set; }
        public int? PaperIssueDate { get; set; }
        public int? PaperDocumentType { get; set; }
        public string Note { get; set; }
        public int? LineCountNumeric { get; set; }
        public string SignatureId { get; set; }
        public string SignatureWebsiteUri { get; set; }
        public int? SignatureAdresId { get; set; }
        public string SignatureRoom { get; set; }
        public string SignatureStreetName { get; set; }
        public int? SignatureBuildingName { get; set; }
        public string SignatureBuildingNumber { get; set; }
        public string SignatureCitySubdivisionName { get; set; }
        public string SignatureCityName { get; set; }
        public string SignaturePostalZone { get; set; }
        public string SignatureRegion { get; set; }
        public string SignatureDistrict { get; set; }
        public string SignatureCountryName { get; set; }
        public string SupplierPhysicalLocationId { get; set; }
        public int? SupplierPhysicalLocationAdresId { get; set; }
        public string SupplierPhysicalLocationRoom { get; set; }
        public string SupplierPhysicalLocationStreetName { get; set; }
        public int? SupplierPhysicalLocationBuildingName { get; set; }
        public string SupplierPhysicalLocationBuildingNumber { get; set; }
        public string SupplierPhysicalLocationCitySubdivisionName { get; set; }
        public string SupplierPhysicalLocationCityName { get; set; }
        public string SupplierPhysicalLocationPostalZone { get; set; }
        public string SupplierPhysicalLocationRegion { get; set; }
        public string SupplierPhysicalLocationDistrict { get; set; }
        public string SupplierPhysicalLocationCountryName { get; set; }
        public string SupplierPartyName { get; set; }
        public string SupplierPartyTaxScheme { get; set; }
        public string SupplierPartyTelephone { get; set; }
        public int? SupplierPartyTelefax { get; set; }
        public string SupplierPartyElectronicMail { get; set; }
        public int? SupplierPartyContactName { get; set; }
        public string SupplierPartyPartyIdentification { get; set; }
        public string Irsaliyekodlist { get; set; }
        public string CustomerPartyId { get; set; }
        public string CustomerPartyTaxScheme { get; set; }
        public string CustomerPartyName { get; set; }
        public string CustomerPartyWebsiteUri { get; set; }
        public string CustomerPartyElectronicMail { get; set; }
        public int? CustomerPartyAdresId { get; set; }
        public int? CustomerPartyRoom { get; set; }
        public string CustomerPartyStreetName { get; set; }
        public int? CustomerPartyBuildingName { get; set; }
        public int? CustomerPartyBuildingNumber { get; set; }
        public int? CustomerPartyApartmentNumber { get; set; }
        public string CustomerPartyCitySubdivisionName { get; set; }
        public string CustomerPartyCityName { get; set; }
        public string CustomerPartyPostalZone { get; set; }
        public string CustomerPartyRegion { get; set; }
        public int? CustomerPartyDistrict { get; set; }
        public string CustomerPartyCountryName { get; set; }
        public string CustomerPartyTelephone { get; set; }
        public string CustomerPartyTelefax { get; set; }
        public string CustomerPartyPartyIdentification { get; set; }
        public string BuyerCustomerPartyId { get; set; }
        public string BuyerCustomerPartyTaxScheme { get; set; }
        public string BuyerCustomerPartyName { get; set; }
        public string BuyerCustomerPartyWebsiteUri { get; set; }
        public string BuyerCustomerPartyElectronicMail { get; set; }
        public int? BuyerCustomerPartyAdresId { get; set; }
        public int? BuyerCustomerPartyRoom { get; set; }
        public string BuyerCustomerPartyStreetName { get; set; }
        public int? BuyerCustomerPartyBuildingName { get; set; }
        public int? BuyerCustomerPartyBuildingNumber { get; set; }
        public int? BuyerCustomerPartyApartmentNumber { get; set; }
        public string BuyerCustomerPartyCitySubdivisionName { get; set; }
        public string BuyerCustomerPartyCityName { get; set; }
        public string BuyerCustomerPartyPostalZone { get; set; }
        public string BuyerCustomerPartyRegion { get; set; }
        public int? BuyerCustomerPartyDistrict { get; set; }
        public string BuyerCustomerPartyCountryName { get; set; }
        public string BuyerCustomerPartyTelephone { get; set; }
        public string BuyerCustomerPartyTelefax { get; set; }
        public string SellerSupplierPartyId { get; set; }
        public string SellerSupplierPartyTaxScheme { get; set; }
        public string SellerSupplierPartyName { get; set; }
        public string SellerSupplierPartyWebsiteUri { get; set; }
        public string SellerSupplierPartyElectronicMail { get; set; }
        public int? SellerSupplierPartyAdresId { get; set; }
        public string SellerSupplierPartyRoom { get; set; }
        public string SellerSupplierPartyStreetName { get; set; }
        public int? SellerSupplierPartyBuildingName { get; set; }
        public string SellerSupplierPartyBuildingNumber { get; set; }
        public int? SellerSupplierPartyApartmentNumber { get; set; }
        public string SellerSupplierPartyCitySubdivisionName { get; set; }
        public string SellerSupplierPartyCityName { get; set; }
        public string SellerSupplierPartyPostalZone { get; set; }
        public string SellerSupplierPartyRegion { get; set; }
        public string SellerSupplierPartyDistrict { get; set; }
        public string SellerSupplierPartyCountryName { get; set; }
        public string SellerSupplierPartyTelephone { get; set; }
        public int? SellerSupplierPartyTelefax { get; set; }
        public int? ShipmentCarrierId { get; set; }
        public int? ShipmentCarrierName { get; set; }
        public int? ShipmentAdresId { get; set; }
        public int? ShipmentRoom { get; set; }
        public int? ShipmentStreetName { get; set; }
        public int? ShipmentBuildingName { get; set; }
        public int? ShipmentBuildingNumber { get; set; }
        public int? ShipmentCitySubdivisionName { get; set; }
        public int? ShipmentCityName { get; set; }
        public int? ShipmentPostalZone { get; set; }
        public int? ShipmentRegion { get; set; }
        public int? ShipmentDistrict { get; set; }
        public int? ShipmentCountryName { get; set; }
        public string ShipmentLicensePlateId { get; set; }
        public double? ShipmentValueAmount { get; set; }
        public string CurrencyCode { get; set; }
        public int ToplamKap { get; set; }
        public string ToplamDarali { get; set; }
        public string ToplamDara { get; set; }
        public string ToplamMiktar { get; set; }
    }
}