using System;

namespace OfisHal.Core.Domain
{
    public class VohalCariKart
    {
        public int CariKartId { get; set; }
        public byte Tip { get; set; }
        public string Kod { get; set; }
        public string KendiKodu { get; set; }
        public string Ad { get; set; }
        public string GsmNo { get; set; }
        public string EPosta { get; set; }
        public string Adres { get; set; }
        public int? PostaKoduId { get; set; }
        public string PostaKodu { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Faks { get; set; }
        public string BankaHesapNo { get; set; }
        public byte KisilikTipi { get; set; }
        public string VergiKimlikNo { get; set; }
        public int? VergiDairesiId { get; set; }
        public string VergiDairesiAdi { get; set; }
        public string MuafiyetBelgeNo { get; set; }
        public DateTime? MuafiyetBitisTarihi { get; set; }
        public string BagkurNo { get; set; }
        public string BabaAdi { get; set; }
        public string Dogum { get; set; }
        public string BorsaSicilNo { get; set; }
        public string Kefil { get; set; }
        public double? Oran { get; set; }
        public double? KdvOrani { get; set; }
        public double Devir { get; set; }
        public int? MarkaId { get; set; }
        public string MarkaAdi { get; set; }
        public int? OrtakId { get; set; }
        public string OrtakAdi { get; set; }
        public double? OrtaklikOrani { get; set; }
        public double? ReeskontOrani { get; set; }
        public string Filtre { get; set; }
        public bool? RusumAlinmasin { get; set; }
        public bool? KesintiAlinmasin { get; set; }
        public string PlakaNo { get; set; }
        public int? BeldeId { get; set; }
        public int? BeldeHksId { get; set; }
        public string BeldeAdi { get; set; }
        public int? IlceId { get; set; }
        public int? IlceHksId { get; set; }
        public string IlceAdi { get; set; }
        public bool? EFaturaBakiyeVar { get; set; }
        public int? IlId { get; set; }
        public int? IlHksId { get; set; }
        public int? UlkeId { get; set; }
        public int? UlkeHksId { get; set; }
        public string IlAdi { get; set; }
        public byte? GidecegiYerTipi { get; set; }
        public int? SehirId { get; set; }
        public string Sehir { get; set; }
        public byte? SatinAlaninSifati { get; set; }
        public int? HalId { get; set; }
        public string HalAdi { get; set; }
        public bool? HalKomisyoncusu { get; set; }
        public bool? Ihracatci { get; set; }
        public int? GidecegiYerWebSiraNo { get; set; }
        public bool? HksBilgisiAlindi { get; set; }
        public byte? EFaturaSenaryosu { get; set; }
        public string Mahalle { get; set; }
        public string Cadde { get; set; }
        public string Sokak { get; set; }
        public string KapiNo { get; set; }
        public string DaireNo { get; set; }
        public string WebAdresi { get; set; }
        public double? VeresiyeSiniri { get; set; }
        public double? RiskSiniri { get; set; }
        public int? CariHesapId { get; set; }
        public string HesapKodu { get; set; }
        public int? DigerHesapId { get; set; }
        public string DigerHesapKodu { get; set; }
        public int? GibEFaturaPostaKutusuId { get; set; }
        public string GibEFaturaPostaKutusu { get; set; }
        public string EFaturaBolgeKodu { get; set; }
        public string EFaturaFaturaKodu { get; set; }
        public int? BolgeKoduId { get; set; }
        public string BolgeKodu { get; set; }
        public string YetkiliKisi { get; set; }
        public int? GeldigiYerId { get; set; }
        public string GeldigiYer { get; set; }
        public int? GunFarki { get; set; }
        public int? FiyatListesiId { get; set; }
        public string FiyatListesiAciklamasi { get; set; }
        public int? YazihaneSiraNo { get; set; }
        public string YazihaneNot { get; set; }
        public int? Vade { get; set; }
        public int? EIrsaliyePostaKutusuId { get; set; }
        public string EIrsaliyePostaKutusu { get; set; }
        public string EFaturaBelgesi { get; set; }
        public string EIrsaliyeBelgesi { get; set; }
        public bool? VergiNoSorgulandi { get; set; }
        public bool? FatKesilmedenKunyeAlinamaz { get; set; }
        public int? SoforId { get; set; }
        public string SoforAdi { get; set; }
        public string SoforTckn { get; set; }
        public byte? HamaliyeHesaplamaSekli { get; set; }
        public byte? NakliyeHesaplamaSekli { get; set; }
        public int? RehinCariKartId { get; set; }
        public string RehinCariKartAdi { get; set; }
        public bool? StopajsizKesebilir { get; set; }
    }
}