//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfisHal.Services.HksUrunSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalinNiteligiIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class MalinNiteligiIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorModel", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Core.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class ErrorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalinNiteligiCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class MalinNiteligiCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.MalinNiteligiDTO> MalinNitelikleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.MalinNiteligiDTO> MalinNitelikleri {
            get {
                return this.MalinNitelikleriField;
            }
            set {
                if ((object.ReferenceEquals(this.MalinNitelikleriField, value) != true)) {
                    this.MalinNitelikleriField = value;
                    this.RaisePropertyChanged("MalinNitelikleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalinNiteligiDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    [System.SerializableAttribute()]
    public partial class MalinNiteligiDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MalinNiteligiAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MalinNiteligiAdi {
            get {
                return this.MalinNiteligiAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MalinNiteligiAdiField, value) != true)) {
                    this.MalinNiteligiAdiField = value;
                    this.RaisePropertyChanged("MalinNiteligiAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunlerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunlerIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunlerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunlerCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunDTO> UrunlerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunDTO> Urunler {
            get {
                return this.UrunlerField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunlerField, value) != true)) {
                    this.UrunlerField = value;
                    this.RaisePropertyChanged("Urunler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    [System.SerializableAttribute()]
    public partial class UrunDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunBirimleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunBirimleriIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunBirimleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunBirimleriCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunBirimiDTO> UrunBirimleriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunBirimiDTO> UrunBirimleri {
            get {
                return this.UrunBirimleriField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunBirimleriField, value) != true)) {
                    this.UrunBirimleriField = value;
                    this.RaisePropertyChanged("UrunBirimleri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunBirimiDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    [System.SerializableAttribute()]
    public partial class UrunBirimiDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunBirimAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunBirimAdi {
            get {
                return this.UrunBirimAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunBirimAdiField, value) != true)) {
                    this.UrunBirimAdiField = value;
                    this.RaisePropertyChanged("UrunBirimAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UretimSekilleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UretimSekilleriIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UretimSekilleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UretimSekilleriCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UretimSekliDTO> UretimSekilleriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UretimSekliDTO> UretimSekilleri {
            get {
                return this.UretimSekilleriField;
            }
            set {
                if ((object.ReferenceEquals(this.UretimSekilleriField, value) != true)) {
                    this.UretimSekilleriField = value;
                    this.RaisePropertyChanged("UretimSekilleri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UretimSekliDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    [System.SerializableAttribute()]
    public partial class UretimSekliDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UretimSekliAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UretimSekliAdi {
            get {
                return this.UretimSekliAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UretimSekliAdiField, value) != true)) {
                    this.UretimSekliAdiField = value;
                    this.RaisePropertyChanged("UretimSekliAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunCinsleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunCinsleriIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UrunIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunId {
            get {
                return this.UrunIdField;
            }
            set {
                if ((this.UrunIdField.Equals(value) != true)) {
                    this.UrunIdField = value;
                    this.RaisePropertyChanged("UrunId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunCinsleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunCinsleriCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunCinsiDTO> UrunCinsleriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunCinsiDTO> UrunCinsleri {
            get {
                return this.UrunCinsleriField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunCinsleriField, value) != true)) {
                    this.UrunCinsleriField = value;
                    this.RaisePropertyChanged("UrunCinsleri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunCinsiDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    [System.SerializableAttribute()]
    public partial class UrunCinsiDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IthalmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UretimSekliIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunCinsiAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UrunIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunKoduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ithalmi {
            get {
                return this.IthalmiField;
            }
            set {
                if ((this.IthalmiField.Equals(value) != true)) {
                    this.IthalmiField = value;
                    this.RaisePropertyChanged("Ithalmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UretimSekliId {
            get {
                return this.UretimSekliIdField;
            }
            set {
                if ((this.UretimSekliIdField.Equals(value) != true)) {
                    this.UretimSekliIdField = value;
                    this.RaisePropertyChanged("UretimSekliId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunCinsiAdi {
            get {
                return this.UrunCinsiAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunCinsiAdiField, value) != true)) {
                    this.UrunCinsiAdiField = value;
                    this.RaisePropertyChanged("UrunCinsiAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunId {
            get {
                return this.UrunIdField;
            }
            set {
                if ((this.UrunIdField.Equals(value) != true)) {
                    this.UrunIdField = value;
                    this.RaisePropertyChanged("UrunId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunKodu {
            get {
                return this.UrunKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunKoduField, value) != true)) {
                    this.UrunKoduField = value;
                    this.RaisePropertyChanged("UrunKodu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunMiktarBirimleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunMiktarBirimleriIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunMiktarBirimleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UrunMiktarBirimleriCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriDTO> UrunMiktarBirimleriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriDTO> UrunMiktarBirimleri {
            get {
                return this.UrunMiktarBirimleriField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunMiktarBirimleriField, value) != true)) {
                    this.UrunMiktarBirimleriField = value;
                    this.RaisePropertyChanged("UrunMiktarBirimleri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunMiktarBirimleriDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    [System.SerializableAttribute()]
    public partial class UrunMiktarBirimleriDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiktarBirimAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MiktarBirimIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UrunIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiktarBirimAd {
            get {
                return this.MiktarBirimAdField;
            }
            set {
                if ((object.ReferenceEquals(this.MiktarBirimAdField, value) != true)) {
                    this.MiktarBirimAdField = value;
                    this.RaisePropertyChanged("MiktarBirimAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MiktarBirimId {
            get {
                return this.MiktarBirimIdField;
            }
            set {
                if ((this.MiktarBirimIdField.Equals(value) != true)) {
                    this.MiktarBirimIdField = value;
                    this.RaisePropertyChanged("MiktarBirimId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunId {
            get {
                return this.UrunIdField;
            }
            set {
                if ((this.UrunIdField.Equals(value) != true)) {
                    this.UrunIdField = value;
                    this.RaisePropertyChanged("UrunId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gtb.gov.tr//WebServices", ConfigurationName="HksUrunSvc.IUrunService")]
    public interface IUrunService {
        
        // CODEGEN: BaseRequestMessageOf_MalinNiteligiIstek iletisinin uyarlama adı (BaseRequestMessageOf_MalinNiteligiIstek) varsayılan değerle (UrunServiceMalinNiteligi) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceMalinNiteligi", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceMalinNiteligiResponse")]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_MalinNiteligiCevap UrunServiceMalinNiteligi(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_MalinNiteligiIstek request);
        
        // CODEGEN: BaseRequestMessageOf_UrunlerIstek iletisinin uyarlama adı (BaseRequestMessageOf_UrunlerIstek) varsayılan değerle (UrunServiceUrunler) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunler", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunlerResponse")]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunlerCevap UrunServiceUrunler(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunlerIstek request);
        
        // CODEGEN: BaseRequestMessageOf_UrunBirimleriIstek iletisinin uyarlama adı (BaseRequestMessageOf_UrunBirimleriIstek) varsayılan değerle (UrunServiceUrunBirimleri) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunBirimleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunBirimleriResponse")]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunBirimleriCevap UrunServiceUrunBirimleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunBirimleriIstek request);
        
        // CODEGEN: BaseRequestMessageOf_UretimSekilleriIstek iletisinin uyarlama adı (BaseRequestMessageOf_UretimSekilleriIstek) varsayılan değerle (UrunServiceUretimSekilleri) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUretimSekilleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUretimSekilleriRespons" +
            "e")]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UretimSekilleriCevap UrunServiceUretimSekilleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UretimSekilleriIstek request);
        
        // CODEGEN: BaseRequestMessageOf_UrunCinsleriIstek iletisinin uyarlama adı (BaseRequestMessageOf_UrunCinsleriIstek) varsayılan değerle (UrunServiceUrunCinsleri) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunCinsleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunCinsleriResponse")]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunCinsleriCevap UrunServiceUrunCinsleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunCinsleriIstek request);
        
        // CODEGEN: BaseRequestMessageOf_UrunMiktarBirimleriIstek iletisinin uyarlama adı (BaseRequestMessageOf_UrunMiktarBirimleriIstek) varsayılan değerle (UrunServiceUrunMiktarBirimleri) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunMiktarBirimleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunMiktarBirimleriRes" +
            "ponse")]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunMiktarBirimleriCevap UrunServiceUrunMiktarBirimleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunMiktarBirimleriIstek request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_MalinNiteligiIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_MalinNiteligiIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OfisHal.Services.HksUrunSvc.MalinNiteligiIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_MalinNiteligiIstek() {
        }
        
        public BaseRequestMessageOf_MalinNiteligiIstek(OfisHal.Services.HksUrunSvc.MalinNiteligiIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_MalinNiteligiCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_MalinNiteligiCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OfisHal.Services.HksUrunSvc.MalinNiteligiCevap Sonuc;
        
        public BaseResponseMessageOf_MalinNiteligiCevap() {
        }
        
        public BaseResponseMessageOf_MalinNiteligiCevap(System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari, string IslemKodu, OfisHal.Services.HksUrunSvc.MalinNiteligiCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunlerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunlerIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OfisHal.Services.HksUrunSvc.UrunlerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunlerIstek() {
        }
        
        public BaseRequestMessageOf_UrunlerIstek(OfisHal.Services.HksUrunSvc.UrunlerIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunlerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunlerCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OfisHal.Services.HksUrunSvc.UrunlerCevap Sonuc;
        
        public BaseResponseMessageOf_UrunlerCevap() {
        }
        
        public BaseResponseMessageOf_UrunlerCevap(System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari, string IslemKodu, OfisHal.Services.HksUrunSvc.UrunlerCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunBirimleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunBirimleriIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OfisHal.Services.HksUrunSvc.UrunBirimleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunBirimleriIstek() {
        }
        
        public BaseRequestMessageOf_UrunBirimleriIstek(OfisHal.Services.HksUrunSvc.UrunBirimleriIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunBirimleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunBirimleriCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OfisHal.Services.HksUrunSvc.UrunBirimleriCevap Sonuc;
        
        public BaseResponseMessageOf_UrunBirimleriCevap() {
        }
        
        public BaseResponseMessageOf_UrunBirimleriCevap(System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari, string IslemKodu, OfisHal.Services.HksUrunSvc.UrunBirimleriCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UretimSekilleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UretimSekilleriIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OfisHal.Services.HksUrunSvc.UretimSekilleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UretimSekilleriIstek() {
        }
        
        public BaseRequestMessageOf_UretimSekilleriIstek(OfisHal.Services.HksUrunSvc.UretimSekilleriIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UretimSekilleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UretimSekilleriCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OfisHal.Services.HksUrunSvc.UretimSekilleriCevap Sonuc;
        
        public BaseResponseMessageOf_UretimSekilleriCevap() {
        }
        
        public BaseResponseMessageOf_UretimSekilleriCevap(System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari, string IslemKodu, OfisHal.Services.HksUrunSvc.UretimSekilleriCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunCinsleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunCinsleriIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OfisHal.Services.HksUrunSvc.UrunCinsleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunCinsleriIstek() {
        }
        
        public BaseRequestMessageOf_UrunCinsleriIstek(OfisHal.Services.HksUrunSvc.UrunCinsleriIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunCinsleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunCinsleriCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OfisHal.Services.HksUrunSvc.UrunCinsleriCevap Sonuc;
        
        public BaseResponseMessageOf_UrunCinsleriCevap() {
        }
        
        public BaseResponseMessageOf_UrunCinsleriCevap(System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari, string IslemKodu, OfisHal.Services.HksUrunSvc.UrunCinsleriCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunMiktarBirimleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunMiktarBirimleriIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunMiktarBirimleriIstek() {
        }
        
        public BaseRequestMessageOf_UrunMiktarBirimleriIstek(OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunMiktarBirimleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunMiktarBirimleriCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriCevap Sonuc;
        
        public BaseResponseMessageOf_UrunMiktarBirimleriCevap() {
        }
        
        public BaseResponseMessageOf_UrunMiktarBirimleriCevap(System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> HataKodlari, string IslemKodu, OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUrunServiceChannel : OfisHal.Services.HksUrunSvc.IUrunService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrunServiceClient : System.ServiceModel.ClientBase<OfisHal.Services.HksUrunSvc.IUrunService>, OfisHal.Services.HksUrunSvc.IUrunService {
        
        public UrunServiceClient() {
        }
        
        public UrunServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrunServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_MalinNiteligiCevap OfisHal.Services.HksUrunSvc.IUrunService.UrunServiceMalinNiteligi(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_MalinNiteligiIstek request) {
            return base.Channel.UrunServiceMalinNiteligi(request);
        }
        
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> UrunServiceMalinNiteligi(OfisHal.Services.HksUrunSvc.MalinNiteligiIstek Istek, string Password, string ServicePassword, string UserName, out string IslemKodu, out OfisHal.Services.HksUrunSvc.MalinNiteligiCevap Sonuc) {
            OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_MalinNiteligiIstek inValue = new OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_MalinNiteligiIstek();
            inValue.Istek = Istek;
            inValue.Password = Password;
            inValue.ServicePassword = ServicePassword;
            inValue.UserName = UserName;
            OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_MalinNiteligiCevap retVal = ((OfisHal.Services.HksUrunSvc.IUrunService)(this)).UrunServiceMalinNiteligi(inValue);
            IslemKodu = retVal.IslemKodu;
            Sonuc = retVal.Sonuc;
            return retVal.HataKodlari;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunlerCevap OfisHal.Services.HksUrunSvc.IUrunService.UrunServiceUrunler(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunlerIstek request) {
            return base.Channel.UrunServiceUrunler(request);
        }
        
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> UrunServiceUrunler(OfisHal.Services.HksUrunSvc.UrunlerIstek Istek, string Password, string ServicePassword, string UserName, out string IslemKodu, out OfisHal.Services.HksUrunSvc.UrunlerCevap Sonuc) {
            OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunlerIstek inValue = new OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunlerIstek();
            inValue.Istek = Istek;
            inValue.Password = Password;
            inValue.ServicePassword = ServicePassword;
            inValue.UserName = UserName;
            OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunlerCevap retVal = ((OfisHal.Services.HksUrunSvc.IUrunService)(this)).UrunServiceUrunler(inValue);
            IslemKodu = retVal.IslemKodu;
            Sonuc = retVal.Sonuc;
            return retVal.HataKodlari;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunBirimleriCevap OfisHal.Services.HksUrunSvc.IUrunService.UrunServiceUrunBirimleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunBirimleriIstek request) {
            return base.Channel.UrunServiceUrunBirimleri(request);
        }
        
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> UrunServiceUrunBirimleri(OfisHal.Services.HksUrunSvc.UrunBirimleriIstek Istek, string Password, string ServicePassword, string UserName, out string IslemKodu, out OfisHal.Services.HksUrunSvc.UrunBirimleriCevap Sonuc) {
            OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunBirimleriIstek inValue = new OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunBirimleriIstek();
            inValue.Istek = Istek;
            inValue.Password = Password;
            inValue.ServicePassword = ServicePassword;
            inValue.UserName = UserName;
            OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunBirimleriCevap retVal = ((OfisHal.Services.HksUrunSvc.IUrunService)(this)).UrunServiceUrunBirimleri(inValue);
            IslemKodu = retVal.IslemKodu;
            Sonuc = retVal.Sonuc;
            return retVal.HataKodlari;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UretimSekilleriCevap OfisHal.Services.HksUrunSvc.IUrunService.UrunServiceUretimSekilleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UretimSekilleriIstek request) {
            return base.Channel.UrunServiceUretimSekilleri(request);
        }
        
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> UrunServiceUretimSekilleri(OfisHal.Services.HksUrunSvc.UretimSekilleriIstek Istek, string Password, string ServicePassword, string UserName, out string IslemKodu, out OfisHal.Services.HksUrunSvc.UretimSekilleriCevap Sonuc) {
            OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UretimSekilleriIstek inValue = new OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UretimSekilleriIstek();
            inValue.Istek = Istek;
            inValue.Password = Password;
            inValue.ServicePassword = ServicePassword;
            inValue.UserName = UserName;
            OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UretimSekilleriCevap retVal = ((OfisHal.Services.HksUrunSvc.IUrunService)(this)).UrunServiceUretimSekilleri(inValue);
            IslemKodu = retVal.IslemKodu;
            Sonuc = retVal.Sonuc;
            return retVal.HataKodlari;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunCinsleriCevap OfisHal.Services.HksUrunSvc.IUrunService.UrunServiceUrunCinsleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunCinsleriIstek request) {
            return base.Channel.UrunServiceUrunCinsleri(request);
        }
        
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> UrunServiceUrunCinsleri(OfisHal.Services.HksUrunSvc.UrunCinsleriIstek Istek, string Password, string ServicePassword, string UserName, out string IslemKodu, out OfisHal.Services.HksUrunSvc.UrunCinsleriCevap Sonuc) {
            OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunCinsleriIstek inValue = new OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunCinsleriIstek();
            inValue.Istek = Istek;
            inValue.Password = Password;
            inValue.ServicePassword = ServicePassword;
            inValue.UserName = UserName;
            OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunCinsleriCevap retVal = ((OfisHal.Services.HksUrunSvc.IUrunService)(this)).UrunServiceUrunCinsleri(inValue);
            IslemKodu = retVal.IslemKodu;
            Sonuc = retVal.Sonuc;
            return retVal.HataKodlari;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunMiktarBirimleriCevap OfisHal.Services.HksUrunSvc.IUrunService.UrunServiceUrunMiktarBirimleri(OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunMiktarBirimleriIstek request) {
            return base.Channel.UrunServiceUrunMiktarBirimleri(request);
        }
        
        public System.Collections.Generic.List<OfisHal.Services.HksUrunSvc.ErrorModel> UrunServiceUrunMiktarBirimleri(OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriIstek Istek, string Password, string ServicePassword, string UserName, out string IslemKodu, out OfisHal.Services.HksUrunSvc.UrunMiktarBirimleriCevap Sonuc) {
            OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunMiktarBirimleriIstek inValue = new OfisHal.Services.HksUrunSvc.BaseRequestMessageOf_UrunMiktarBirimleriIstek();
            inValue.Istek = Istek;
            inValue.Password = Password;
            inValue.ServicePassword = ServicePassword;
            inValue.UserName = UserName;
            OfisHal.Services.HksUrunSvc.BaseResponseMessageOf_UrunMiktarBirimleriCevap retVal = ((OfisHal.Services.HksUrunSvc.IUrunService)(this)).UrunServiceUrunMiktarBirimleri(inValue);
            IslemKodu = retVal.IslemKodu;
            Sonuc = retVal.Sonuc;
            return retVal.HataKodlari;
        }
    }
}
